adding rehydration corral, which replaces a node in a given rke2 cluster
rancherlabs/corral-packages pull request #5
Opened 2022-12-06 20:18 UTC by slickwarren

This is a supporting PR for rancher automation: https://github.com/rancher/rancher/pull/39752

2023-02-14 17:47 UTC, jakefhyde requested changes
`.DS_STORE` files need to be removed, also some minor formatting issues. Also, the corral_node_pools should probably be updated once the node has been removed. This looks like it doesn't remove a node so much as delete it and add the same node back, is that intended? I imagine for rehydration we want to test with new nodes being added to the cluster.

2023-02-14 17:47 UTC, jakefhyde commented on templates/aws-replace-node/terraform/pools/main.tf
> +  subnet_id = var.aws_subnet
```suggestion
  count                  = var.replace_count
  ami                    = var.aws_ami
  instance_type          = var.instance_type
  key_name               = aws_key_pair.corral_key.key_name
  vpc_security_group_ids = [var.aws_security_group]
  subnet_id              = var.aws_subnet
```
Formatting, I generally use a terraform plugin for whatever IDE I'm using and it should format it correctly.

2023-02-14 17:47 UTC, jakefhyde commented on templates/rke2-replace-node/overlay/opt/corral/rke2/delete_nodes.sh
> +#1/bin/bash
```suggestion
#!/bin/bash
```
Also should be `delete-nodes.sh`

2023-02-14 18:14 UTC, slickwarren commented
spoke offline, the rehydration is resolved in the kubeconfig file as part of this package.

2023-02-14 18:44 UTC, jakefhyde approved these changes

2023-02-15 16:17 UTC, sbstp approved these changes

2023-02-15 16:47 UTC, merged